//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlytaloMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Valot
    {
        public int ValoId { get; set; }
        public bool ValoOff { get; set; }
        public bool Valo33 { get; set; }
        public bool Valo66 { get; set; }
        public bool Valo100 { get; set; }
        public Nullable<System.DateTime> ValoOffAika { get; set; }
        public Nullable<System.DateTime> Valo33Aika { get; set; }
        public Nullable<System.DateTime> Valo66AIka { get; set; }
        public Nullable<System.DateTime> valo100Aika { get; set; }
        public string HuoneValo { get; set; }
    }
}
